services:
  client:
    build: ./client
    ports: ['3000:80']
    depends_on: [server]

  server:
    build: ./server
    ports: ['4000:4000']
    environment:
      MONGODB_URI: mongodb://mongo:27017/albion-map
    depends_on: [mongo]

  mongo:
    image: mongo:7
    ports: ['27017:27017']
    volumes: [mongo-data:/data/db]

volumes:
  mongo-data:
